### ISSUE TITLE
Defense/Dodge shoulder enchants wrong or missing

### ISSUE THREAD

**Issue by jonarnar** [mobmentality67/mobmentality67.github.io#11]
Greater Inscription of Warding is increasing the EHP value and crit chance instead of increasing EHP and reducing Incoming Crit Chance.
Greater Inscription of Warding links to the wrong wowhead page.
The other defense/dodge shoulder enchants are missing.

**Comment by mobmentality67** [comment]
Thanks -- it looks like there was a copy paste error for Greater Inscription of Warding -> Greater Inscription of the Knight. These should be corrected now -- also made the shoulder enchants point to the item, not the spell, so the icon and description is a little cleaner.
