### ISSUE TITLE
Bad of Eternal Champion overvalued?

### ISSUE THREAD

**Issue by crezax** [mobmentality67/mobmentality67.github.io#19]
Band of Eternal Champion shows suspiciously high increase of TPS.

I compared it to Band of Eternity. The difference between the 2 is 10 AP, 4 agi and proc (160 AP for 10 sec every 1 min).

The difference between those 2 items is 47.6 TPS according to the sim:

<img width="1398" alt="Screen Shot 2021-11-07 at 11 03 58" src="https://user-images.githubusercontent.com/3847084/140640669-fa3575bf-c37e-4cee-b0bd-44a964e58efe.png">

This is about 170 AP worth of stats according to the "custom" tab:
<img width="1400" alt="Screen Shot 2021-11-07 at 11 02 57" src="https://user-images.githubusercontent.com/3847084/140640695-c9e1b5ff-cdd8-4035-9813-5c40123538f1.png">

This leads me to believe that the sim assumes 100% proc uptime for Band of Eternal Champion

**Comment by mobmentality67** [comment]
Hi Crezax,

You are correct -- there was a bug where the Band of the Eternal Champion, after proccing, stayed active. I just pushed a fix. Thanks!
