### ISSUE TITLE
Spymistress' Wristguards

### ISSUE THREAD

**Issue by Cameronza** [mobmentality67/mobmentality67.github.io#20]
This piece of gear on the sim has 15 hit rating, but this stat is missing from the piece of gear on the sim.
![TiE4xzq](https://user-images.githubusercontent.com/17275831/140646204-a25c752a-40f5-414e-b162-fb7c0327e64d.png)

**Comment by mobmentality67** [comment]
Good catch -- fixed. Thanks!
