### ISSUE TITLE
Errors in Stats of item 

### ISSUE THREAD

**Issue by shotguny** [mobmentality67/mobmentality67.github.io#22]
Hi!

Vindicator's drangonhide boots and leather boots have identical stats in your program,

even each boots are not same in game.

So it's simcraft result shows same TPS and EHP..

Plz fix it..

Thank you for this program all time since I started Feral druid in TBC.

Bye!!

**Comment by mobmentality67** [comment]
Thanks, I corrected this. Vindicator's Leather Boots appear to already have correctly matched the in-game version, Dragonhide was accidentally copy-pasted from Leather and not fixed. Dragonhide should have the correct stats now.
