### ISSUE TITLE
Striking ring enchant on Ring 2 has wrong spellid

### ISSUE THREAD

**Issue by theochemtheo** [mobmentality67/mobmentality67.github.io#24]
The spellid here is wrong, it is currently 45159, which is the spellid for 4 stats
https://github.com/mobmentality67/mobmentality67.github.io/blob/master/js/data/gear.js#L3358

I think the correct spell id is 27920, which is what it is a few lines above
https://github.com/mobmentality67/mobmentality67.github.io/blob/master/js/data/gear.js#L3340

**Comment by mobmentality67** [comment]
Late replying to this but it's been fixed. Thank you!
