### ISSUE TITLE
Bug: Vindicator's Dragonhide Belt does not account for crit chance

### ISSUE THREAD

**Issue by joaomcarlos** [mobmentality67/mobmentality67.github.io#28]
Hi,

I just got myself a Vindicator's Dragonhide Belt because I think its awesome.

Your simulator puts it at a much worse ranking compared to alternatives, like the "Vindicator's Leather Belt".

I believe that the problem is that the crit rating benefit of 21 (0.95%) is not accounted for, making it appear lower.

Once thats changed to account for the crit rating I expect the sim value for it to raise dramatically. Probably to the 2nd or 3rd position, and because its much easier to get than the raiding alternatives, it seems quite important to have it correctly calculated for newbie durids :)

**Comment by mobmentality67** [comment]
Added
