### ISSUE TITLE
Using incorrect vanilla armor forumla

### ISSUE THREAD

**Issue by zidnae** [mobmentality67/mobmentality67.github.io#9]
https://github.com/mobmentality67/mobmentality67.github.io/blob/83572db4eb78091599754ee7b963aec764b2bc9a/cpp/player.cpp#L478

Was updated in TBC
https://wowwiki-archive.fandom.com/wiki/Armor?oldid=1435631

**Comment by mobmentality67** [comment]
These are looking at the .cpp which is deprecated. I need to remove the .cpp entirely, I'll file another issue for that
